#!/usr/bin/env python3
"""Run pipeline with file-based logging — minimal memory, no LLM title gen."""
import sys, json, time, traceback
from pathlib import Path

PROJECT_DIR = '/home/z/my-project/work/extracted/TestProduceGen_bdd_v29'
sys.path.insert(0, PROJECT_DIR)
import os
os.chdir(PROJECT_DIR)

LOG = Path('/tmp/run_progress.log')
LOG.write_text('')

def log(msg):
    with open(LOG, 'a') as f:
        f.write(f'[{time.strftime("%H:%M:%S")}] {msg}\n')

try:
    log('START')
    # Disable LLM by setting empty API key env
    os.environ['LLM_API_KEY'] = ''
    # Also neutralize config.json
    if Path('config.json').exists():
        Path('config.json.bak').write_text(Path('config.json').read_text())
        cfg = json.loads(Path('config.json').read_text())
        cfg['llm']['api_key'] = ''
        Path('config.json').write_text(json.dumps(cfg, ensure_ascii=False, indent=2))
        log('LLM API key disabled in config.json')
    
    from graph import compile_p3_graph
    log('Imports OK')
    
    app = compile_p3_graph()
    log('Graph compiled')
    
    state = {
        'coverage_model_path': 'obligation_coverage_model.json',
        'warnings': [],
        'errors': [],
        'current_stage': 'init',
        'messages': [],
    }
    log('Streaming graph...')
    result = dict(state)
    for event in app.stream(state, config={'recursion_limit': 100}):
        for node_name, node_output in event.items():
            result.update(node_output)
            stage = node_output.get('current_stage', node_name)
            n = len(result.get('procedures') or [])
            log(f'Stage {stage}: {n} procedures')
    log(f'Done! Procedures: {len(result.get("procedures", []))}')
    
    # Save output (skip title — those will be regenerated by main.py later)
    out_path = '/tmp/run_output.json'
    es_keys = ['primary_entity','phase_table','dep_state_phase_map','contextual_phase_rules',
               'state_type_map','dependent_entities','entity_parent','dependency_depth',
               'topology_levels','virtual_entities','transition_upstream_map']
    engine_state = {k: result.get(k) for k in es_keys if result.get(k) is not None}
    out = {
        'engine_state': engine_state,
        'procedures': result.get('procedures', []),
        'warnings': result.get('warnings', []),
        'errors': result.get('errors', []),
        'entity_instance_counts': result.get('entity_instance_counts', {}),
    }
    with open(out_path, 'w') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    log(f'Saved to {out_path} (size={Path(out_path).stat().st_size} bytes)')
except Exception as e:
    log(f'ERROR: {e}')
    log(traceback.format_exc())

