#!/usr/bin/env python3
"""Run pipeline with file-based logging — minimal memory, no LLM title gen.

B-06: 删除旧版的硬编码外部机器路径与破坏性 config.json 改写——无 LLM 模式
用环境变量 LLM_API_KEY='' 覆盖即可（main.py 读取顺序为 环境变量 > config.json），
不再备份/置空仓库配置，也不产生 .bak 密钥泄露面。
"""
import sys, json, time, traceback, os
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_DIR))
os.chdir(PROJECT_DIR)

LOG = Path(__file__).resolve().parent.parent / 'run_progress.log'
LOG.write_text('')

def log(msg):
    with open(LOG, 'a', encoding='utf-8') as f:
        f.write(f'[{time.strftime("%H:%M:%S")}] {msg}\n')

try:
    log('START')
    # 无 LLM 模式：仅用环境变量覆盖，不改写仓库 config.json
    os.environ['LLM_API_KEY'] = ''
    log('LLM API key disabled via env override (config.json untouched)')

    from graph import compile_p3_graph
    log('Imports OK')

    app = compile_p3_graph()
    log('Graph compiled')

    state = {
        'coverage_model_path': 'obligation_coverage_model.json',
        'warnings': [],
        'errors': [],
        'current_stage': 'init',
        'messages': [],
    }
    log('Streaming graph...')
    result = dict(state)
    for event in app.stream(state, config={'recursion_limit': 100}):
        for node_name, node_output in event.items():
            result.update(node_output)
            stage = node_output.get('current_stage', node_name)
            n = len(result.get('procedures') or [])
            log(f'Stage {stage}: {n} procedures')
    log(f'Done! Procedures: {len(result.get("procedures", []))}')

    # Save output (skip title — those will be regenerated by main.py later)
    out_path = PROJECT_DIR / 'run_output.json'
    es_keys = ['primary_entity','phase_table','dep_state_phase_map','contextual_phase_rules',
               'state_type_map','dependent_entities','entity_parent','dependency_depth',
               'topology_levels','virtual_entities']
    engine_state = {k: result.get(k) for k in es_keys if result.get(k) is not None}
    out = {
        'engine_state': engine_state,
        'procedures': result.get('procedures', []),
        'warnings': result.get('warnings', []),
        'errors': result.get('errors', []),
        'entity_instance_counts': result.get('entity_instance_counts', {}),
    }
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    log(f'Saved to {out_path} (size={Path(out_path).stat().st_size} bytes)')
except Exception as e:
    log(f'ERROR: {e}')
    log(traceback.format_exc())
